### ISSUE TITLE
Elapsed time and ETA

### ISSUE THREAD

**Issue by henrik** [henrik/progress_bar#2]
If there's a sensible way of doing this. Maybe running the progress bar as a server? That could also enable us to have a `tick(progress_to_add)` type interface like https://github.com/tj/node-progress.

**Comment by praveenperera** [comment]
It would be cool to add the download speed as well, like in the mechanize progress bar: https://github.com/kitamomonga/Mechanize-ProgressBar

**Comment by henrik** [comment]
@praveenperera :thumbsup: Sounds good. I also like the idea of Mechanize progress bar – I might make a httpoison_progress_bar for fun some day. Basically combining this lib with https://gist.github.com/henrik/108e5fc23b66131fc3aa, automagically showing an indeterminate bar if there's no content length.

**Comment by henrik** [comment]
Closing this since I don't think I'll get around to it, but if anyone else wants to, feel free!
