### ISSUE TITLE
Improve documentation on hexdocs

### ISSUE THREAD

**Issue by kelvinst** [henrik/progress_bar#20]
Since elixir libs all have a good documentation, I guess we should follow the language standards right? ;)

**Comment by henrik** [comment]
I agree this would be nice! I'm so used to documenting in the README that I'm less comfortable with docs alongside the code, but I should try :) Things are hectic right now but I'll leave this ticket open.

**Comment by henrik** [comment]
I will close this since I'm not maintaining this lib very actively and don't plan on spending time on this, but PRs are still welcome.
