### ISSUE TITLE
Lots of line-breaks when terminal window is too narrow

### ISSUE THREAD

**Issue by martinsvalin** [henrik/progress_bar#9]
Progress bars are pretty wide. When the terminal window is too narrow for them, they print each update on its own line. I don't know the exact break point, but 80 columns is too narrow and will show this bug.

```
$ mix run examples/01-default.exs

Default bar:
|=
|==
|===
|====
|=====
etc…
```

**Comment by henrik** [comment]
Good point. I have considered auto-detecting terminal width at some point.

Seems ruby-progressbar has this figured out: https://github.com/jfelchner/ruby-progressbar/wiki/Overriding-the-Length

**Comment by henrik** [comment]
Seems `tput cols` in a terminal will get us the number of columns: http://stackoverflow.com/questions/263890/how-do-i-find-the-width-height-of-a-terminal-window
- [x] Basic accounting for for left, right, percentage and "bytes"
- [x] Account for unprintable characters when determining widths
- [x] Handle "tput cols" not being available (e.g. Windows)
- [ ] WONTFIX: Account for length of "bytes" being variable ("0.00 MB/123.00 MB" -> "122.00/123 MB" -> "123 MB")

**Comment by henrik** [comment]
Considering this done. @martinsvalin, if you have the inclination, try it out and let me know how it works for you!
